# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJH6nxMcXBGn_n_8VvlLTrDQzFIeFesB
"""

import streamlit as st
import pickle
import numpy as np

# Load trained model
with open("diabetes_logistic_model.pkl", "rb") as file:
    model = pickle.load(file)

# Page configuration
st.set_page_config(page_title="Diabetes Prediction",page_icon="🩺",layout="centered")

# Title
st.title("🩺 Diabetes Prediction using Logistic Regression")

st.write(
    "Enter the patient's information below to predict "
    "the likelihood of diabetes."
)

# User inputs
pregnancies = st.number_input("Pregnancies",min_value=0,max_value=20,value=1)

glucose = st.number_input("Glucose",min_value=0,max_value=300,value=120)

blood_pressure = st.number_input("Blood Pressure",min_value=0,max_value=200,value=70)

skin_thickness = st.number_input("Skin Thickness",min_value=0,max_value=100,value=20)

insulin = st.number_input("Insulin",min_value=0,max_value=900,value=80)

bmi = st.number_input("BMI",min_value=0.0,max_value=70.0,value=25.0)

diabetes_pedigree = st.number_input("Diabetes Pedigree Function",min_value=0.0,max_value=3.0,value=0.47)

age = st.number_input("Age",min_value=1,max_value=120,value=30)

# Prediction button
if st.button("Predict Diabetes"):

    # Create input array
    input_data = np.array([[
        pregnancies,
        glucose,
        blood_pressure,
        skin_thickness,
        insulin,
        bmi,
        diabetes_pedigree,
        age
    ]])

    # Prediction
    prediction = model.predict(input_data)[0]

    # Prediction probability
    probability = model.predict_proba(input_data)[0][1]

    # Display result
    st.subheader("Prediction Result")

    if prediction == 1:
        st.error("⚠️ Diabetes Detected")
    else:
        st.success("✅ No Diabetes Detected")

    st.write(
        f"Probability of diabetes: **{probability * 100:.2f}%**"
    )