# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJH6nxMcXBGn_n_8VvlLTrDQzFIeFesB
"""
import streamlit as st
import pandas as pd
import joblib

# Load model and scaler
model1 = joblib.load("diabetes_logistic_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Diabetes Prediction")

st.write("Enter patient details")

pregnancies = st.number_input(
    "Pregnancies",
    min_value=0,
    value=1
)

glucose = st.number_input(
    "Glucose",
    min_value=0.0,
    value=120.0
)

blood_pressure = st.number_input(
    "Blood Pressure",
    min_value=0.0,
    value=70.0
)

skin_thickness = st.number_input(
    "Skin Thickness",
    min_value=0.0,
    value=20.0
)

insulin = st.number_input(
    "Insulin",
    min_value=0.0,
    value=80.0
)

bmi = st.number_input(
    "BMI",
    min_value=0.0,
    value=30.0
)

diabetes_pedigree = st.number_input(
    "Diabetes Pedigree Function",
    min_value=0.0,
    value=0.47
)

age = st.number_input(
    "Age",
    min_value=1,
    value=30
)


if st.button("Predict"):

    input_data = pd.DataFrame({
        "Pregnancies": [pregnancies],
        "Glucose": [glucose],
        "BloodPressure": [blood_pressure],
        "SkinThickness": [skin_thickness],
        "Insulin": [insulin],
        "BMI": [bmi],
        "DiabetesPedigreeFunction": [diabetes_pedigree],
        "Age": [age]
    })

    # Scale input using the saved scaler
    input_scaled = scaler.transform(input_data)

    # Prediction
    prediction = model1.predict(input_scaled)[0]

    # Probability
    probability = model1.predict_proba(input_scaled)[0][1]

    st.subheader("Prediction Result")

    st.write(
        f"Diabetes Probability: {probability:.2%}"
    )

    if prediction == 1:
        st.error("Prediction: Diabetes")
    else:
        st.success("Prediction: No Diabetes")

